server:
  port: 9001

spring:
  application:
    name: xdclass-user-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: localhost:8848


  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xdclass_user?serverTimezone=Asia/Shanghai
    username: root
    password: GY
  redis:
    database: 0
    host: localhost
    port: 6379

  mail:
    host: smtp.126.com #发送邮件服务器
    username: gy1961237983@126.com #发送邮件的邮箱地址
    password: SJYDTEOSVCFRWECB    #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: gy1961237983@126.com # 发送邮件的地址，和上面username一致

    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

#阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t7BHkVbEKLq4spBjN8V
    access-key-secret: 4bW4qn17H23Bp6hV4zEdA9ze66Nex8
    bucketname: gy-xdclass-1024shop-img


##seata配置
#seata:
#  tx-service-group: ${spring.application.name}-group
#  service:
#    grouplist:
#      xdclass: 127.0.0.1:8091
#    vgroup-mapping:
#      xdclass-user-service-group: xdclass